// <auto-generated />
using System;
using AODMS.Models.DailyLog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AODMS.Migrations
{
    [DbContext(typeof(DailyLogDbContext))]
    partial class DailyLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AODMS.Models.DailyLog.DailyLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .IsRequired();

                    b.Property<string>("Entry")
                        .IsRequired();

                    b.Property<int>("LogSummaryId");

                    b.HasKey("Id");

                    b.ToTable("DailyLogEntries");
                });

            modelBuilder.Entity("AODMS.Models.DailyLog.DailyLogLocation", b =>
                {
                    b.Property<string>("Unit")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Unit");

                    b.ToTable("DailyLogLocations");
                });

            modelBuilder.Entity("AODMS.Models.DailyLog.DailyLogSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CertifiedBy");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Unit")
                        .IsRequired();

                    b.Property<string>("ValidatedBy");

                    b.HasKey("Id");

                    b.ToTable("DailyLogSummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
